services:
  workspace:
    build:
      dockerfile: .devcontainer/dockerfile
      context: ..
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    depends_on:
      - database
    environment:
      - ENV
      - APP_PORT
      - SERVER_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_HOST
      - DB_PORT
      - DB_SSL_MODE
      - TEST_DB_USER
      - TEST_DB_PASS
      - TEST_DB_NAME
    command: sleep infinity
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"

  database:
    image: docker.io/postgres:16
    command: -p ${DB_PORT}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DB_USER
      - DB_PASS
      - DB_NAME
      - TEST_DB_USER
      - TEST_DB_PASS
      - TEST_DB_NAME
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ../tasks-server/.devcontainer/dbinit:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
